// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// The `Message` type represents a chat message with an ID, text content,
// and the timestamp when it was created.
type Message struct {
	ID        string `json:"id"`
	Text      string `json:"text"`
	CreatedAt string `json:"createdAt"`
}

// The root `Query` type must contain at least one field for introspection to work in the playground.
type Query struct {
}

// The `Subscription` type defines all subscriptions available
// to clients. You can use Schema Directives to restrict access
// as needed.
type Subscription struct {
}

// The `Time` type represents the current time, including both a
// Unix epoch timestamp and a string timestamp.
type Time struct {
	Unix      int32  `json:"unix"`
	Timestamp string `json:"timestamp"`
}
